[project]
name = "semaptic"
description = "helper for exploratory viz of CSV text data with embeddings + PaCMAP" 
version = "0.0.7"
authors = [
    { name = "Jeremy Merrill", email = "jeremy.merrill@washpost.com" },
]
dependencies = [
    "pandas ~= 2.3.1",
    "openai >= 1.107.3",
    "google-genai >= 1.56.0",
    "scikit-learn",
    "umap-learn",
    "dash >= 3.2.0",
    "nbformat>=4.2.0",
    "itables",
    "plotly",
    "pacmap",
]

[tool.uv.sources]
pacmap = { git = "https://github.com/Tyrannas/PaCMAP.git" }
